"""Layered knowledge runtime primitives."""

from nanobot.knowledge.base import (
    APIKnowledgeAdapter,
    BaseKnowledgeSourceAdapter,
    CLIKnowledgeAdapter,
    FilesystemKnowledgeAdapter,
    KnowledgeCompiler,
    KnowledgeRetentionPolicy,
    MCPKnowledgeAdapter,
    KnowledgeSourceAdapter,
    KnowledgeStore,
    WebKnowledgeAdapter,
)
from nanobot.knowledge.contracts import (
    KnowledgeArtifact,
    KnowledgeCandidate,
    KnowledgeClaimType,
    KnowledgeIngestRequest,
    KnowledgeIngestResult,
    KnowledgeKind,
    KnowledgeLayer,
    KnowledgePlatform,
    KnowledgeQuery,
    KnowledgeRetentionDecision,
    KnowledgeStatus,
    KnowledgeSourceSpec,
)
from nanobot.knowledge.filesystem_store import FilesystemKnowledgeStore
from nanobot.knowledge.fusion import KnowledgeExpansionJob, KnowledgeExpansionWorker, KnowledgeFusionManager
from nanobot.knowledge.obsidian import ObsidianFrontend
from nanobot.knowledge.pipeline import (
    InMemoryKnowledgeStore,
    KnowledgeAdapterRegistry,
    KnowledgeRuntime,
    NullKnowledgeStore,
    PassthroughKnowledgeCompiler,
    SimpleKnowledgeRetentionPolicy,
)
from nanobot.knowledge.xiaohongshu import (
    XiaohongshuCLI,
    XiaohongshuCollectionResult,
    XiaohongshuKnowledgeAdapter,
    XiaohongshuKnowledgeCollector,
    build_topic_scan_note,
)

__all__ = [
    "BaseKnowledgeSourceAdapter",
    "APIKnowledgeAdapter",
    "FilesystemKnowledgeAdapter",
    "CLIKnowledgeAdapter",
    "FilesystemKnowledgeStore",
    "InMemoryKnowledgeStore",
    "KnowledgeExpansionJob",
    "KnowledgeExpansionWorker",
    "KnowledgeFusionManager",
    "KnowledgeAdapterRegistry",
    "KnowledgeArtifact",
    "KnowledgeCandidate",
    "KnowledgeClaimType",
    "KnowledgeCompiler",
    "KnowledgeIngestRequest",
    "KnowledgeIngestResult",
    "KnowledgeKind",
    "KnowledgeLayer",
    "KnowledgePlatform",
    "KnowledgeQuery",
    "KnowledgeRetentionDecision",
    "KnowledgeRetentionPolicy",
    "KnowledgeRuntime",
    "KnowledgeStatus",
    "KnowledgeSourceAdapter",
    "KnowledgeSourceSpec",
    "KnowledgeStore",
    "MCPKnowledgeAdapter",
    "NullKnowledgeStore",
    "ObsidianFrontend",
    "PassthroughKnowledgeCompiler",
    "SimpleKnowledgeRetentionPolicy",
    "WebKnowledgeAdapter",
    "XiaohongshuCLI",
    "XiaohongshuCollectionResult",
    "XiaohongshuKnowledgeAdapter",
    "XiaohongshuKnowledgeCollector",
    "build_topic_scan_note",
]
